# Generated by Django 3.0.5 on 2021-02-07 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICES'), ('VIAJES', 'Viajes'), ('COMIDA', 'COMIDA'), ('DEPORTES', 'DEPORTES'), ('OTHERS', 'OTHERS')], max_length=255)),
                ('precios', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('descripcion', models.TextField()),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
