# Generated by Django 3.0.5 on 2021-02-07 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('SALARIO', 'SALARIO'), ('EMPLEO', 'EMPLEO'), ('T-EXTRA', 'T-EXTRA'), ('OTHERS', 'OTHERS')], max_length=255)),
                ('precios', models.DecimalField(decimal_places=2, max_digits=10, max_length=255)),
                ('descripcion', models.TextField()),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
